name: Pipeline
run-name: ${{ github.event.head_commit.message }}
on: [push]

env:
  STAGE: main
  REGION: us-east-1

jobs:
  Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Install project
        run: npm ci --silent
      - if: github.ref == 'refs/heads/main'
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
      - if: github.ref == 'refs/heads/main'
        name: Fetch database secret
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            DB_SECRET, arn:aws:secretsmanager:us-east-1:008908697155:secret:ezmc-user-service/main/rds-Hl1Hpc
          parse-json-secrets: true
      - if: github.ref == 'refs/heads/main'
        name: Migrate database schema # requires IAM service role for RDS
        env:
          DB_URL: postgresql://$DB_SECRET_USERNAME:$DB_SECRET_PASSWORD@ezmc-user-service-main.c1z3yesb8dwk.us-east-1.rds.amazonaws.com:5432/postgres
        run: npx prisma migrate deploy
      - name: Deploy serverless functions # requires AWS access key
        if: github.ref == 'refs/heads/main'
        env:
          DB_URL: postgresql://$DB_SECRET_USERNAME:$DB_SECRET_PASSWORD@ezmc-user-service-main.c1z3yesb8dwk.us-east-1.rds.amazonaws.com:5432/postgres
        run: npx serverless deploy --stage $STAGE --region $REGION
